val url="mongodb://local:27017/perftrace.analysis_day"
spark.sql("create database if not exists perftrace")
spark.sql("use perftrace")
spark.read.format("com.mongodb.spark.sql").options(Map("uri"-> url,"partitioner"->"MongoPaginateBySizePartitioner")).load().registerTempTable("mongo_analysis_day")
spark.sql("create table if not exists analysis_day(pt_user string,pt_service string,pt_code string,pt_ip string,pt_user_ip string,pt_date string,pt_count int) partitioned by (dir0 string) stored as parquet")
spark.sql("alter table analysis_day drop if exists partition (dir0='201505')")
spark.sql("insert into table analysis_day partition (dir0='201505') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20150501' and pt_date<'20150601'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201506')")
spark.sql("insert into table analysis_day partition (dir0='201506') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20150601' and pt_date<'20150701'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201507')")
spark.sql("insert into table analysis_day partition (dir0='201507') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20150701' and pt_date<'20150801'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201508')")
spark.sql("insert into table analysis_day partition (dir0='201508') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20150801' and pt_date<'20150901'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201509')")
spark.sql("insert into table analysis_day partition (dir0='201509') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20150901' and pt_date<'20151001'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201510')")
spark.sql("insert into table analysis_day partition (dir0='201510') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20151001' and pt_date<'20151101'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201511')")
spark.sql("insert into table analysis_day partition (dir0='201511') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20151101' and pt_date<'20151201'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201512')")
spark.sql("insert into table analysis_day partition (dir0='201512') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20151201' and pt_date<'20160101'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201601')")
spark.sql("insert into table analysis_day partition (dir0='201601') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160101' and pt_date<'20160201'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201602')")
spark.sql("insert into table analysis_day partition (dir0='201602') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160201' and pt_date<'20160301'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201603')")
spark.sql("insert into table analysis_day partition (dir0='201603') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160301' and pt_date<'20160401'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201604')")
spark.sql("insert into table analysis_day partition (dir0='201604') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160401' and pt_date<'20160501'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201605')")
spark.sql("insert into table analysis_day partition (dir0='201605') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160501' and pt_date<'20160601'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201606')")
spark.sql("insert into table analysis_day partition (dir0='201606') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160601' and pt_date<'20160701'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201607')")
spark.sql("insert into table analysis_day partition (dir0='201607') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160701' and pt_date<'20160801'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201608')")
spark.sql("insert into table analysis_day partition (dir0='201608') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160801' and pt_date<'20160901'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201609')")
spark.sql("insert into table analysis_day partition (dir0='201609') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20160901' and pt_date<'20161001'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201610')")
spark.sql("insert into table analysis_day partition (dir0='201610') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20161001' and pt_date<'20161101'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201611')")
spark.sql("insert into table analysis_day partition (dir0='201611') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20161101' and pt_date<'20161201'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201612')")
spark.sql("insert into table analysis_day partition (dir0='201612') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20161201' and pt_date<'20170101'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201701')")
spark.sql("insert into table analysis_day partition (dir0='201701') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170101' and pt_date<'20170201'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201702')")
spark.sql("insert into table analysis_day partition (dir0='201702') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170201' and pt_date<'20170301'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201703')")
spark.sql("insert into table analysis_day partition (dir0='201703') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170301' and pt_date<'20170401'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201704')")
spark.sql("insert into table analysis_day partition (dir0='201704') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170401' and pt_date<'20170501'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201705')")
spark.sql("insert into table analysis_day partition (dir0='201705') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170501' and pt_date<'20170601'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201706')")
spark.sql("insert into table analysis_day partition (dir0='201706') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170601' and pt_date<'20170701'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201707')")
spark.sql("insert into table analysis_day partition (dir0='201707') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170701' and pt_date<'20170801'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201708')")
spark.sql("insert into table analysis_day partition (dir0='201708') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170801' and pt_date<'20170901'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201709')")
spark.sql("insert into table analysis_day partition (dir0='201709') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20170901' and pt_date<'20171001'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201710')")
spark.sql("insert into table analysis_day partition (dir0='201710') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20171001' and pt_date<'20171101'")
spark.sql("alter table analysis_day drop if exists partition (dir0='201711')")
spark.sql("insert into table analysis_day partition (dir0='201711') select pt_user,pt_service,pt_code,pt_ip,pt_user_ip,pt_date,pt_count from mongo_analysis_day where pt_date>='20171101' and pt_date<'20171201'")
